### PR TITLE
Introducing IBuildContext

### PR DESCRIPTION
**Pull request by ygel**
User-defined object that flows through dependency chain.
Context object should be specified on the "parent" task, which then flow it to dependents.
Optionally, context object passed to any of the dependents will be used from then on down the chain.

### CODE REVIEW

**Comment by adamralph** [comment]
@ygel thanks for raising this.

If I understand correctly, it seems this can be done today by declaring a variable, e.g.:

```c#
var context = new Dictionary<string, object>();

Target("foo", () => context["bar"] = 42));

Target("baz", DependsOn("foo"), () => Console.WriteLine(context["bar"])));
```

Is there something else that this change provides that I am missing?

**Comment by ygel** [comment]
Hello, in a simple case, yes you can just create context locally and pass it to each target that requires it. What I'm after is slightly more involved and this feature is critical for encapsulation and DRY reasons. Implicit context flow feature and  overload of `RunTargets...`  that accepts a context object are important to have targets that can be freely reused. 

I am building an installer pack for [Elastic Beats](https://www.elastic.co/products/beats). Nature of the beast is such that there are many products and each product has multiple variations along with other distinguishing factors that need to be established before build can begin. Version information is determined by hitting build artifact API and is highly dynamic Having a target for every combination is understandably impractical, hence this implementation was born. Last, but certainly not the least: CI builds are very important, thus information I can store with the build system itself is very limited.

Having targets that can accept context would allow me to run individual sub-targets like find a snapshot or a versioned build, download only and unpack, etc., for one or more products as well as running a mid-level target for a specific product (and/or set) or a top-level `all` target.

I appreciate your quick reply and would like to see this feature through, thanks!

**Comment by adamralph** [comment]
@ygel I think I understand the need for such a context in more advanced scenarios, but I'm not sure I understand why this context has to be passed into the `Run..` methods only to be passed back to the target delegates. If you want to build reusable methods to call in target delegates, they can take a parameter of `Dictionary<string, object>` or whatever other type context object you want to inject. If I understand correctly, Bullseye would never interrogate or mutate the context, it would simply accept it in one method and pass it out when calling other methods (the target delegates). That sounds to me like a form of poor-man's dependency injection, and doesn't need to live in Bullseye. For example, you could create your `Dictionary<string, object>` in your entry point, and pass it around as required, or you could build your own singleton which everything could reference, or you could even use something like https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.

But perhaps I'm still missing something. Could you maybe give a concrete example of something you cannot do with the current API, and could only do with your proposed API?

**Comment by ygel** [comment]
Let me address the `Run` point first. Assume targets A, B, C, where B depends on A and C depends on A. B and C have different contexts they operate on (think different urls, products, etc), and they want to reuse A, passing their own context for A to work on. Presently Bullseye will only run A once, when B runs, it will not run A again when C runs. `Run` overload is a mechanism to accomplish that, although at a loss of explicit dependency chain.

**Comment by adamralph** [comment]
> Assume targets A, B, C, where B depends on A and C depends on A. B and C have different contexts they operate on (think different urls, products, etc), and they want to reuse A, passing their own context for A to work on.

What you are describing is rather different to the dependency model of Bullseye, and every other build target/task type tool I know of (e.g. Make, Rake, Fake, Cake, etc).

> Presently Bullseye will only run A once, when B runs, it will not run A again when C runs.

Indeed, this is the target/task dependency model followed by Bullseye and all other similar tools I know of.

It sounds like what you need are just method calls. I.e. two targets, A and B which both call a method C, passing in any parameters required, one of which can be the "context" object you are describing?

**Comment by ygel** [comment]
> What you are describing is rather different to the dependency model of Bullseye, and every other build target/task type tool I know of (e.g. Make, Rake, Fake, Cake, etc).

Well, other build tools are also aware of produced artifacts/outputs. This is where the problem lies I believe. Bullseye's targets are not able to check if output is valid/present in addition to tracking the dependency graph. 

I was hoping to build a data-driven tree of tasks that bullseye understands (and prints with `-t`) and allow for running that tree from any point.

**Comment by adamralph** [comment]
@ygel I believe I now understand what you want from this. You want to specify that B depends on A with context X, and C depends on A with context Y. That is:

- When it is time to run B, A is first run with context X, and then B is run.
- When it is time to run C, A has not already been run with context Y, so A is first run with context Y and then C is run.

Is that correct?

**Comment by ygel** [comment]
> * When it is time to run B, A is first run with context X, and then B is run.
> * When it is time to run C, A has not already been run with context Y, so A is first run with context Y and then C is run.

Correct, to clarify: Contexts X and Y must factor into decision of whether to run dependencies along with "did this task already run" flag. Also appropriate context object must flow from A to B/C.

Thanks!

**Comment by adamralph** [comment]
OK, I'll have to give this a little thought. It's quite a change to how Bullseye works and it introduces some interesting API considerations.

BTW I don't think this PR currently does what you want, since the tasks which represent running targets are keyed only name and not by name and context: https://github.com/ygel/bullseye/blob/3bace4e5e25362efe17703213ec02cda888f9674/Bullseye/Internal/TargetCollection.cs#L86

**Comment by ygel** [comment]
> BTW I don't think this PR currently does what you want, since the tasks which represent running targets are keyed only name and not by name and context: https://github.com/ygel/bullseye/blob/3bace4e5e25362efe17703213ec02cda888f9674/Bullseye/Internal/TargetCollection.cs#L86


That's correct, I tried to work around this with adding context to the Run... methods.

Since this is taking a while with my PR, I am exploring another option, however hit another problem: there's no way to remove targets once target collection is built. I can't build and destroy dependency trees on the fly.

**Comment by adamralph** [comment]
> there's no way to remove targets once target collection is built. I can't build and destroy dependency trees on the fly.

Correct. Bullseye was not designed with anything like that mind.

BTW so you don't get the wrong expectation, if something like this feaure does make it into Bullseye it may not happen any time soon. As I said, this requires some careful thinking regarding the API and also consideration of the complexity it introduces. It may not even be possible without some fundamental, and possibly breaking, changes.

**Comment by adamralph** [comment]
> I can't build and destroy dependency trees on the fly.

@ygel I wouldn't be opposed to adding a `ClearTargets` method.

**Comment by ygel** [comment]
> > I can't build and destroy dependency trees on the fly.
> 
> @ygel I wouldn't be opposed to adding a `ClearTargets` method.

@adamralph That would be great, thank you!

**Pull request closed without merging**
