### PR TITLE
API for integration with third party CLI libs

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
@johncrim I've released this in [3.2.0-alpha.1](https://www.nuget.org/packages/Bullseye/3.2.0-alpha.1). Care to give it a try? See the smoke testers for examples of how to use the new API:

- [System.CommandLine.Experimental](https://github.com/adamralph/bullseye/blob/master/BullseyeSmokeTester.Experimental/Program.cs)
- [System.CommandLine.DragonFruit](https://github.com/adamralph/bullseye/blob/master/BullseyeSmokeTester.DragonFruit/Program.cs)
- [McMaster.Extensions.CommandLineUtils](https://github.com/adamralph/bullseye/blob/master/BullseyeSmokeTester.McMaster/Program.cs)

**Comment by johncrim** [comment]
@adamralph - thank you! Yes, I will try it out in the next few days.

**Comment by johncrim** [comment]
@adamralph - I've integrated `3.2.0-alpha2` with `System.CommandLine.Experimental` latest prerelease version for our builds. It works great! It's nice to see our custom command-line switches alongside the bullseye ones when running `--help`.

The only minor nitpick is that the nice coloring that BullsEye provides for `--help` output doesn't show in `System.CommandLine.Experimental` help output, but that's on System.CommandLine.Experimental.

I haven't yet tested using different command-line switches for different build targets, but it seems like that case should work fine with the approach you've taken.

Thank you for the very useful library!

**Comment by adamralph** [comment]
@johncrim that's great to hear! Thanks very much for the feedback.

**Pull request merged**
